SV인베스트먼트:
  - 에스브이인베스트먼트
  - SV Investment
한국투자파트너스:
  - Korea Investment Partners
  - KIP
NAVER WEBTOON:
  - 네이버웹툰
  - WEBTOON
Kakao Entertainment:
  - 카카오엔터테인먼트
  - 카카오엔터
SM Entertainment:
  - SM엔터테인먼트
  - 에스엠엔터테인먼트
HYBE:
  - 하이브
JYP Entertainment:
  - JYP엔터테인먼트
MUNPIA:
  - 문피아
Wavve:
  - 웨이브
  - 콘텐츠웨이브
